In [59]:
# loading in modules
import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# creating file path
dbfile = 'hc3-metadata-tables/hc3-tables.db'
# Create a SQL connection to our SQLite database
con = sqlite3.connect(dbfile)

# creating cursor
cur = con.cursor()

# reading all table names
table_list = [a for a in cur.execute("SELECT name FROM sqlite_master WHERE type = 'table'")]
# here is you table list
print(table_list)
df = pd.read_sql_query('SELECT * FROM cell', con)
# Be sure to close the connection
con.close()

[('session',), ('epos',), ('file',), ('cell',)]


In [55]:

for i in range(12):
    f = open(f'gor01-6-13/2006-6-13_15-44-7/2006-6-13_15-44-7.res.{i+1}','r').read()
    spike_times = np.array([int(string) for string in f.split('\n')[:-1]])
    
    f = open(f'gor01-6-13/2006-6-13_15-44-7/2006-6-13_15-44-7.clu.{i+1}','r').read()
    cluster = np.array([int(string) for string in f.split('\n')[:-1]])

    print(spike_times[-1])
#     plt.scatter(spike_times, np.ones(len(spike_times)))
# spike_times[-1]

84017113
84016836
84016739
84016908
84016998
84016251
84016397
84016827
84016944
84017059
84016996
84016991


In [71]:
# df[df['behavior']=='wheel']

In [83]:
df[df['topdir']=='gor01-6-13']

id      topdir animal  ele  clu region  nexciting  ninhibiting  \
6474  6665  gor01-6-13  gor01    1    2    CA3          0            0   
6475  6666  gor01-6-13  gor01    1    3    CA3          0            0   
6476  6667  gor01-6-13  gor01    1    4    CA3          1            0   
6477  6668  gor01-6-13  gor01    1    5    CA3          0            0   
6478  6669  gor01-6-13  gor01    1    6    CA3          1            0   
6479  6670  gor01-6-13  gor01    2    2    CA3          0            0   
6480  6671  gor01-6-13  gor01    2    3    CA3          0            0   
6481  6672  gor01-6-13  gor01    2    4    CA3          0            0   
6482  6673  gor01-6-13  gor01    2    5    CA3          0            0   
6483  6674  gor01-6-13  gor01    2    6    CA3          0            0   
6484  6675  gor01-6-13  gor01    2    7    CA3          0            0   
6485  6676  gor01-6-13  gor01    2    8    CA3          0            0   
6486  6677  gor01-6-13  gor01    2    9    CA3          0            0   
6487  6678  gor01-6-13  gor01    2   10    CA3          0            0   
6488  6679  gor01-6-13  gor01    2   11    CA3          0            0   
6489  6680  gor01-6-13  gor01    2   12    CA3          0            0   
6490  6681  gor01-6-13  gor01    2   13    CA3          1            0   
6491  6682  gor01-6-13  gor01    2   14    CA3          0            1   
6492  6683  gor01-6-13  gor01    2   15    CA3          0            0   
6493  6684  gor01-6-13  gor01    3    2    CA3          0            0   
6494  6685  gor01-6-13  gor01    3    3    CA3          1            0   
6495  6686  gor01-6-13  gor01    4    2    CA3          0            0   
6496  6687  gor01-6-13  gor01    4    3    CA3          0            0   
6497  6688  gor01-6-13  gor01    4    4    CA3          0            0   
6498  6689  gor01-6-13  gor01    4    5    CA3          0            0   
6499  6690  gor01-6-13  gor01    8    2    CA3          0            0   
6500  6691  gor01-6-13  gor01    8    3    CA3          1            0   
6501  6692  gor01-6-13  gor01    8    4    CA3          1            0   
6502  6693  gor01-6-13  gor01    8    5    CA3          0            0   
6503  6694  gor01-6-13  gor01    8    6    CA3          0            0   
6504  6695  gor01-6-13  gor01    8    7    CA3          1            0   
6505  6696  gor01-6-13  gor01    8    8    CA3          0            0   
6506  6697  gor01-6-13  gor01    8    9    CA3          0            0   
6507  6698  gor01-6-13  gor01    8   10    CA3          1            0   
6508  6699  gor01-6-13  gor01    8   11    CA3          0            3   
6509  6700  gor01-6-13  gor01    8   12    CA3          2            0   
6510  6701  gor01-6-13  gor01    8   13    CA3          1            0   
6511  6702  gor01-6-13  gor01    8   14    CA3          0            0   
6512  6703  gor01-6-13  gor01    8   15    CA3          0            0   
6513  6704  gor01-6-13  gor01    8   16    CA3          0            0   
6514  6705  gor01-6-13  gor01    8   17    CA3          1            0   
6515  6706  gor01-6-13  gor01    8   18    CA3          0            0   
6516  6707  gor01-6-13  gor01    8   19    CA3          2            0   
6517  6708  gor01-6-13  gor01    8   20    CA3          0            0   
6518  6709  gor01-6-13  gor01    9    2    CA1          0            0   
6519  6710  gor01-6-13  gor01    9    3    CA1          1            0   
6520  6711  gor01-6-13  gor01    9    4    CA1          0            0   
6521  6712  gor01-6-13  gor01    9    5    CA1          0            0   
6522  6713  gor01-6-13  gor01    9    6    CA1          0            0   
6523  6714  gor01-6-13  gor01   10    2    CA1          0            0   
6524  6715  gor01-6-13  gor01   10    3    CA1          0            1   
6525  6716  gor01-6-13  gor01   10    4    CA1          1            0   
6526  6717  gor01-6-13  gor01   10    5    CA1          0            0   
6527  6718  

In [74]:
f = open(f'gor01-6-13/2006-6-13_15-44-7/2006-6-13_15-44-7.res.1','r').read()
spike_times = np.array([int(string) for string in f.split('\n')[:-1]])

f = open(f'gor01-6-13/2006-6-13_15-44-7/2006-6-13_15-44-7.clu.1','r').read()
cluster = np.array([int(string) for string in f.split('\n')[1:-1]])

In [82]:
for i in range(12):
    f = open(f'gor01-6-13/2006-6-13_15-44-7/2006-6-13_15-44-7.clu.{i+1}','r').read()
    cluster = np.array([int(string) for string in f.split('\n')[1:-1]])
    print(np.unique(cluster))

[0 1 2 3 4 5 6]
[ 0  1  2  4  5  7  8 10 11 12 13 14 15]
[0 1 2 3]
[0 1 2 3 4 5]
[0 1]
[0 1]
[0 1]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[0 1 3 4 6]
[0 1 2 3 4 5]
[0 1]
[0 1 4 5 6]
